# Generated by Django 3.1.3 on 2020-11-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201113_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ticket',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.event'),
        ),
    ]
