# Generated by Django 3.1.3 on 2020-11-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_event_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='payment_method',
        ),
    ]
